### PR TITLE
Bitmex orderbook needs to track tick ids

### PR DESCRIPTION
**Pull request by norbert-gaulia**

### CODE REVIEW

**Comment by beijunyi** [comment]
WebSocketMessageParser is to determine the type of an incoming message. If you want to track the ID of an orderbook update. You can track it in your subscriber.

**Comment by norbertas-gaulia** [comment]
Need the reference to action, that is outside of message array.
nHk8adQ

**Comment by norbertas-gaulia** [comment]
> Need the reference to action, that is outside of message array.
 I realized i can derive from current event: price is null -> action `delete`, price not null -> id exists ? `update` : `insert`

**Comment by norbertas-gaulia** [comment]
> Need the reference to action, that is outside of message array.

I realized i can derive from message:
Size null, Price null -> `delete`
Size !null, Price null -> `update`
Size !null, Price !null ->`insert`

**Pull request closed without merging**
