### PR TITLE
Add Fills for FTX

### PR DESCRIPTION
**Pull request by mayankpunetha007**
Fills should be retrieved for when websocket disconnects

### CODE REVIEW

**Comment by oleksiilogvin** [comment]
> Fills should be retrieved for when websocket disconnects
How is this comment related to changes you made?
By the way, nice addition.
Besides, I suspect you are not using "google-java-format" plugin, recommended by project authors.

**Comment by oleksiilogvin** [comment]
Check out corrected version of GetFills class: https://github.com/oleksiilogvin/io.contek.invoker/commit/9b15d0a0d8447334557d714a2a69ed653ff73aa9#diff-7aff39f33173740a1c03840b8f2508198eb04c116cef079301f346df4e05f27b

**Comment by Fenrur** [comment]
It's already in my pull request #34

**Review by pimpcapital — APPROVED** [review]
Thank you for your contribution. Will include this in the next release.

**Pull request merged**
